### ISSUE TITLE
Create Worker projects

### ISSUE THREAD

**Issue by derabbink** [derabbink/DistrEx#1]
**Worker Interface definition**
DistrEx.Worker.Interface (C# class library)
DistrEx.Worker.Interface.Test (test project, add a nuget reference to nunit)

**Worker (non-default) implementation and extensions**
DisrEx.Worker (C# class library, add reference to DistrEx.Worker.Interface)
DistrEx.Worker.Test (test project, add a nuget reference to nunit)

**Comment by fasalex** [comment]
Code pushed.
