### ISSUE TITLE
transport debug information

### ISSUE THREAD

**Issue by derabbink** [derabbink/DistrEx#25]
In addition to transporting just DLLs, DistrEx should also transport PDBs, XMLs and potentially other files (.config) that match a transported assembly's filename.

Example:
If an assembly `My.Library, version=1.0.0.0, Culture=neutral, PublicKeyToken=0123456789ABCDEF` located in `my assembly-v1.0.dll` is tranported to a worker, any existing `my assembly-v1.0.pdb` (and other extensions) should be transported as well.

**Comment by fasalex** [comment]
No need to transfer the config files.
